package domain

import "errors"

var (
	ErrInvalidCredentials        = errors.New("invalid credentials")
	ErrEmailAlreadyExists        = errors.New("email already exists")
	ErrNotFound                  = errors.New("not found")
	ErrUnauthorized              = errors.New("unauthorized")
	ErrInvalidOAuthState         = errors.New("invalid oauth state")
	ErrProviderDisabled          = errors.New("provider disabled")
	ErrInvalidEmail              = errors.New("invalid email format")
	ErrPasswordPolicy            = errors.New("password does not meet policy requirements")
	ErrRateLimited               = errors.New("rate limited")
	ErrVerificationToken         = errors.New("invalid email verification token")
	ErrResetToken                = errors.New("invalid password reset token")
	ErrMFARequired               = errors.New("mfa required")
	ErrMFAInvalidCode            = errors.New("invalid mfa code")
	ErrWorkspaceNotFound         = errors.New("workspace not found")
	ErrWorkspaceAccessDenied     = errors.New("workspace access denied")
	ErrMembershipNotFound        = errors.New("membership not found")
	ErrMembershipManageDenied    = errors.New("membership manage denied")
	ErrInvitationNotFound        = errors.New("invitation not found")
	ErrInvitationExpired         = errors.New("invitation expired")
	ErrInvitationAccepted        = errors.New("invitation already accepted")
	ErrLastOwnerCannotBeRemoved  = errors.New("last owner cannot be removed")
	ErrInvitationPayloadInvalid  = errors.New("invitation payload invalid")
	ErrInvalidRole               = errors.New("invalid role")
	ErrRoleNotFound              = errors.New("role not found")
	ErrRoleManageDenied          = errors.New("role manage denied")
	ErrRoleNameConflict          = errors.New("role name conflict")
	ErrPermissionSetInvalid      = errors.New("permission set invalid")
	ErrPermissionRegistryUnknown = errors.New("permission registry unknown")
	ErrRoleAssignmentConflict    = errors.New("role assignment conflict")
	ErrSessionNotOwned           = errors.New("session not owned by user")
	ErrInvalidWorkspaceName      = errors.New("invalid workspace name")
	ErrWorkspaceNameConflict     = errors.New("workspace name already exists")
	ErrInvalidPermissionMask     = errors.New("permission mask contains unknown bits")
)
