package api

const (
	errCodeInternal = "internal.error"

	errCodeAuthInvalidRequestBody       = "auth.invalid_request_body"
	errCodeAuthInvalidToken             = "auth.invalid_token"
	errCodeAuthInvalidCredentials       = "auth.invalid_credentials"
	errCodeAuthPermissionDenied         = "auth.permission_denied"
	errCodeAuthRateLimited              = "auth.rate_limited"
	errCodeAuthOAuthStateInvalid        = "auth.oauth_state_invalid"
	errCodeAuthVerificationTokenInvalid = "auth.verification_token_invalid"
	errCodeAuthResetTokenInvalid        = "auth.reset_token_invalid"
	errCodeAuthMFARequired              = "auth.mfa_required"
	errCodeAuthMFAInvalidCode           = "auth.mfa_invalid_code"
	errCodeAuthProviderNotSupported     = "auth.provider_not_supported"
	errCodeAuthSessionNotOwned          = "auth.session_not_owned"
	errCodeAuthPasswordPolicyViolation  = "auth.password_policy_violation"

	errCodeAPIKeyInvalid        = "api_key.invalid"
	errCodeAPIKeyRateLimited    = "api_key.rate_limited"
	errCodeAPIKeyScopeDenied    = "api_key.scope_denied"
	errCodeAPIKeyManageDenied   = "api_key.manage_denied"
	errCodeAPIKeyNotFound       = "api_key.not_found"
	errCodeAPIKeyRotateConflict = "api_key.rotate_conflict"
	errCodeAPIKeyScopeInvalid   = "api_key.scope_invalid"
	errCodeAPIKeyConfigInvalid  = "api_key.config_invalid"

	errCodeDeliveryReadDenied                   = "delivery.read_denied"
	errCodeDeliveryQueryInvalid                 = "delivery.query_invalid"
	errCodeDeliveryMessageNotFound              = "delivery.message_not_found"
	errCodeDeliveryRequestBodyInvalid           = "delivery.request_body_invalid"
	errCodeDeliveryTransactionalRequestNotFound = "delivery.transactional_request_not_found"
	errCodeDeliveryIdempotencyKeyConflict       = "delivery.idempotency_key_conflict"
	errCodeDeliveryRecipientInvalid             = "delivery.recipient_invalid"
	errCodeDeliveryRecipientSuppressed          = "delivery.recipient_suppressed"
	errCodeDeliveryModeInvalid                  = "delivery.mode_invalid"
	errCodeDeliveryRawBodyRequired              = "delivery.raw_body_required"
	errCodeDeliveryAttachmentTooLarge           = "delivery.attachment_too_large"
	errCodeDeliveryDuplicateRecipient           = "delivery.duplicate_recipient"
	errCodeDeliverySubjectRequired              = "delivery.subject_required"
	errCodeDeliveryAttachmentNotSupported       = "delivery.attachment_not_supported"
	errCodeDeliveryAttachmentStorageFailed      = "delivery.attachment_storage_failed"
	errCodeDeliveryObjectStorageDisabled        = "delivery.object_storage_disabled"
	errCodeDeliveryQuotaExceeded                = "delivery.quota_exceeded"
	errCodeDeliveryTemporarilyUnavailable       = "delivery.temporarily_unavailable"

	errCodeWebhookManageDenied                 = "webhook.manage_denied"
	errCodeWebhookConfigNotFound               = "webhook.config_not_found"
	errCodeWebhookTargetURLInvalid             = "webhook.target_url_invalid"
	errCodeWebhookSubscriptionInvalid          = "webhook.subscription_invalid"
	errCodeWebhookConfigInvalid                = "webhook.config_invalid"
	errCodeWebhookConfigNameConflict           = "webhook.config_name_conflict"
	errCodeWebhookRotateConflict               = "webhook.rotate_conflict"
	errCodeWebhookDeliveryReadDenied           = "webhook.delivery_read_denied"
	errCodeWebhookDeliveryRetryDenied          = "webhook.delivery_retry_denied"
	errCodeWebhookDeliveryNotFound             = "webhook.delivery_not_found"
	errCodeWebhookDeliveryRetryConflict        = "webhook.delivery_retry_conflict"
	errCodeWebhookConfigDisabled               = "webhook.config_disabled"
	errCodeWebhookPayloadInvalid               = "webhook.payload_invalid"
	errCodeWebhookProviderNotSupported         = "webhook.provider_not_supported"
	errCodeWebhookInvalidSignature             = "webhook.invalid_signature"
	errCodeWebhookDuplicateEventConflict       = "webhook.duplicate_event_conflict"
	errCodeWebhookIngestTemporarilyUnavailable = "webhook.ingest_temporarily_unavailable"

	errCodeIdentityWorkspaceNotFound         = "identity.workspace_not_found"
	errCodeIdentityWorkspaceAccessDenied     = "identity.workspace_access_denied"
	errCodeIdentityMembershipNotFound        = "identity.membership_not_found"
	errCodeIdentityMembershipManageDenied    = "identity.membership_manage_denied"
	errCodeIdentityInvitationNotFound        = "identity.invitation_not_found"
	errCodeIdentityInvitationTokenExpired    = "identity.invitation_token_expired"
	errCodeIdentityInvitationAlreadyAccepted = "identity.invitation_already_accepted"
	errCodeIdentityInvitationPayloadInvalid  = "identity.invitation_payload_invalid"
	errCodeIdentityLastOwnerCannotBeRemoved  = "identity.last_owner_cannot_be_removed"
	errCodeIdentityRoleNotFound              = "identity.role_not_found"
	errCodeIdentityRoleManageDenied          = "identity.role_manage_denied"
	errCodeIdentityRoleNameConflict          = "identity.role_name_conflict"
	errCodeIdentityPermissionSetInvalid      = "identity.permission_set_invalid"
	errCodeIdentityPermissionRegistryUnknown = "identity.permission_registry_unknown"
	errCodeIdentityRoleAssignmentConflict    = "identity.role_assignment_conflict"
	errCodeIdentityInvalidPermissionMask     = "identity.invalid_permission_mask"
	errCodeIdentityInvalidWorkspaceName      = "identity.invalid_workspace_name"
	errCodeIdentityWorkspaceNameConflict     = "identity.workspace_name_conflict"
	errCodeIdentityEmailAlreadyRegistered    = "identity.email_already_registered"

	errCodeSenderDomainNotFound         = "sender.domain_not_found"
	errCodeSenderDomainNotVerified      = "sender.domain_not_verified"
	errCodeSenderManageDenied           = "sender.manage_denied"
	errCodeSenderDomainConflict         = "sender.domain_conflict"
	errCodeSenderInvalidStateTransition = "sender.invalid_state_transition"
	errCodeSenderDomainInvalid          = "sender.domain_invalid"
	errCodeSenderProviderConfigInvalid  = "sender.provider_config_invalid"

	errCodeTemplateNotFound              = "template.not_found"
	errCodeTemplateReadDenied            = "template.read_denied"
	errCodeTemplateWriteDenied           = "template.write_denied"
	errCodeTemplateRenderDenied          = "template.render_denied"
	errCodeTemplateVersionNotFound       = "template.version_not_found"
	errCodeTemplatePublishConflict       = "template.publish_conflict"
	errCodeTemplateVersionConflict       = "template.version_conflict"
	errCodeTemplateSourceInvalid         = "template.source_invalid"
	errCodeTemplatePublishPayloadInvalid = "template.publish_payload_invalid"
	errCodeTemplateRenderPayloadInvalid  = "template.render_payload_invalid"
	errCodeTemplateRenderContextInvalid  = "template.render_context_invalid"

	errCodeCampaignReadDenied             = "campaign.read_denied"
	errCodeCampaignWriteDenied            = "campaign.write_denied"
	errCodeCampaignSendDenied             = "campaign.send_denied"
	errCodeCampaignNotFound               = "campaign.not_found"
	errCodeCampaignPayloadInvalid         = "campaign.payload_invalid"
	errCodeCampaignAudienceNotReady       = "campaign.audience_not_ready"
	errCodeCampaignInvalidStateTransition = "campaign.invalid_state_transition"

	errCodeAudienceReadDenied                   = "audience.read_denied"
	errCodeAudienceWriteDenied                  = "audience.write_denied"
	errCodeAudienceImportDenied                 = "audience.import_denied"
	errCodeAudienceExportDenied                 = "audience.export_denied"
	errCodeAudienceExportUnavailable            = "audience.export_unavailable"
	errCodeAudienceContactNotFound              = "audience.contact_not_found"
	errCodeAudienceListNotFound                 = "audience.list_not_found"
	errCodeAudienceSegmentNotFound              = "audience.segment_not_found"
	errCodeAudienceImportJobNotFound            = "audience.import_job_not_found"
	errCodeAudienceExportJobNotFound            = "audience.export_job_not_found"
	errCodeAudienceContactEmailConflict         = "audience.contact_email_conflict"
	errCodeAudienceListNameConflict             = "audience.list_name_conflict"
	errCodeAudienceSegmentNameConflict          = "audience.segment_name_conflict"
	errCodeAudienceImportDuplicateSubmission    = "audience.import_duplicate_submission"
	errCodeAudienceContactPayloadInvalid        = "audience.contact_payload_invalid"
	errCodeAudienceContactStatusInvalid         = "audience.contact_status_invalid"
	errCodeAudienceSegmentDefinitionInvalid     = "audience.segment_definition_invalid"
	errCodeAudienceListMembershipPayloadInvalid = "audience.list_membership_payload_invalid"
	errCodeAudienceImportSourceInvalid          = "audience.import_source_invalid"
	errCodeAudienceExportFilterInvalid          = "audience.export_filter_invalid"
	errCodeAudienceExportFormatInvalid          = "audience.export_format_invalid"

	errCodeOperationsQueueReadDenied          = "operations.queue_read_denied"
	errCodeOperationsDLQReadDenied            = "operations.dlq_read_denied"
	errCodeOperationsReplayManageDenied       = "operations.replay_manage_denied"
	errCodeOperationsFilterInvalid            = "operations.filter_invalid"
	errCodeOperationsReplayTargetInvalid      = "operations.replay_target_invalid"
	errCodeOperationsOutboxRecordNotFound     = "operations.outbox_record_not_found"
	errCodeOperationsDeadLetterRecordNotFound = "operations.dead_letter_record_not_found"
	errCodeOperationsReplayJobNotFound        = "operations.replay_job_not_found"
	errCodeOperationsReplayConflict           = "operations.replay_conflict"

	errCodeSettingsPayloadInvalid  = "settings.payload_invalid"
	errCodeSettingsManageDenied    = "settings.manage_denied"
	errCodeSettingsVersionConflict = "settings.version_conflict"

	errCodeTrackingInvalidTrackingID          = "tracking.invalid_tracking_id"
	errCodeSuppressionUnsubscribeTokenInvalid = "suppression.unsubscribe_token_invalid"

	errCodeNotificationFilterInvalid       = "notification.filter_invalid"
	errCodeNotificationRealtimeUnavailable = "notification.realtime_unavailable"
	errCodeNotificationReadDenied          = "notification.read_denied"
	errCodeNotificationNotFound            = "notification.not_found"

	errCodeSuppressionReadDenied         = "suppression.read_denied"
	errCodeSuppressionManageDenied       = "suppression.manage_denied"
	errCodeSuppressionEntryNotFound      = "suppression.entry_not_found"
	errCodeSuppressionUnsuppressConflict = "suppression.unsuppress_conflict"
	errCodeSuppressionScopeInvalid       = "suppression.scope_invalid"
	errCodeSuppressionReasonInvalid      = "suppression.reason_invalid"

	errCodeAuditReadDenied    = "audit.read_denied"
	errCodeAuditFilterInvalid = "audit.filter_invalid"

	errCodeAnalyticsQueryInvalid       = "analytics.query_invalid"
	errCodeAnalyticsStoreUnavailable   = "analytics.store_unavailable"
	errCodeAnalyticsProjectionNotFound = "analytics.projection_not_found"
	errCodeAnalyticsReadDenied         = "analytics.read_denied"
)
